// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using teste.Data;

#nullable disable

namespace teste.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("teste.Models.CanteiroObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevisaoTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("CanteirosObra");
                });

            modelBuilder.Entity("teste.Models.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AreaTotal")
                        .HasColumnType("double precision");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanteiroObraId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DepositoCoberto")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsavelNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CanteiroObraId");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("teste.Models.EstoqueMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepositoId")
                        .HasColumnType("integer");

                    b.Property<string>("LocalizacaoNoDeposito")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<double>("QuantidadeDisponivel")
                        .HasColumnType("double precision");

                    b.Property<double?>("QuantidadeMaxima")
                        .HasColumnType("double precision");

                    b.Property<double?>("QuantidadeMinima")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("DepositoId", "MaterialId")
                        .IsUnique();

                    b.ToTable("EstoquesMateriais");
                });

            modelBuilder.Entity("teste.Models.HistoricoSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataMudanca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LatitudeNoMomento")
                        .HasColumnType("double precision");

                    b.Property<double?>("LongitudeNoMomento")
                        .HasColumnType("double precision");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataMudanca");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("HistoricosSolicitacao");
                });

            modelBuilder.Entity("teste.Models.ItemSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendido")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double precision");

                    b.Property<double?>("QuantidadeEntregue")
                        .HasColumnType("double precision");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("ItensSolicitacao");
                });

            modelBuilder.Entity("teste.Models.LocalSolicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AreaConstruida")
                        .HasColumnType("double precision");

                    b.Property<double?>("AreaTerreno")
                        .HasColumnType("double precision");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanteiroObraId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PercentualConclusao")
                        .HasColumnType("integer");

                    b.Property<string>("Quadra")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoConstrucao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CanteiroObraId");

                    b.HasIndex("Identificador");

                    b.ToTable("LocaisSolicitacao");
                });

            modelBuilder.Entity("teste.Models.Maquinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanteiroObraId")
                        .HasColumnType("integer");

                    b.Property<double>("CapacidadeCarga")
                        .HasColumnType("double precision");

                    b.Property<double?>("CapacidadeVolume")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataProximaManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaAtualizacaoGPS")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Odometro")
                        .HasColumnType("double precision");

                    b.Property<int?>("OperadorAtualId")
                        .HasColumnType("integer");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<double?>("VelocidadeAtual")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CanteiroObraId");

                    b.HasIndex("Nome");

                    b.ToTable("Maquinarios");
                });

            modelBuilder.Entity("teste.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Fornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("PesoUnitario")
                        .HasColumnType("double precision");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("integer");

                    b.Property<double?>("VolumeUnitario")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("teste.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApontadorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanteiroObraId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNecessidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepositoId")
                        .HasColumnType("integer");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LocalSolicitacaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaquinarioId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroSolicitacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacoesApontador")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApontadorId");

                    b.HasIndex("CanteiroObraId");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("DepositoId");

                    b.HasIndex("LocalSolicitacaoId");

                    b.HasIndex("MaquinarioId");

                    b.HasIndex("NumeroSolicitacao")
                        .IsUnique();

                    b.HasIndex("SolicitadorId");

                    b.HasIndex("Status");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("teste.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanteiroObraId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanteiroObraId");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<int>("TipoUsuario").HasValue(4);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("teste.Models.Apontador", b =>
                {
                    b.HasBaseType("teste.Models.Usuario");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Usuarios", t =>
                        {
                            t.Property("Matricula")
                                .HasColumnName("Apontador_Matricula");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("teste.Models.OperadorMaquinario", b =>
                {
                    b.HasBaseType("teste.Models.Usuario");

                    b.Property<string>("CNH")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CategoriaCNH")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("MaquinarioAtualId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidadeCNH")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("MaquinarioAtualId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("teste.Models.Solicitador", b =>
                {
                    b.HasBaseType("teste.Models.Usuario");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("teste.Models.CanteiroObra", b =>
                {
                    b.OwnsOne("teste.Models.Localizacao", "LocalizacaoCentral", b1 =>
                        {
                            b1.Property<int>("CanteiroObraId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("CanteiroObraId");

                            b1.ToTable("CanteirosObra");

                            b1.WithOwner()
                                .HasForeignKey("CanteiroObraId");
                        });

                    b.Navigation("LocalizacaoCentral")
                        .IsRequired();
                });

            modelBuilder.Entity("teste.Models.Deposito", b =>
                {
                    b.HasOne("teste.Models.CanteiroObra", "CanteiroObra")
                        .WithMany("Depositos")
                        .HasForeignKey("CanteiroObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("teste.Models.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("DepositoId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("DepositoId");

                            b1.ToTable("Depositos");

                            b1.WithOwner()
                                .HasForeignKey("DepositoId");
                        });

                    b.Navigation("CanteiroObra");

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("teste.Models.EstoqueMaterial", b =>
                {
                    b.HasOne("teste.Models.Deposito", "Deposito")
                        .WithMany("EstoqueMateriais")
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teste.Models.Material", "Material")
                        .WithMany("EstoquesMateriais")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deposito");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("teste.Models.HistoricoSolicitacao", b =>
                {
                    b.HasOne("teste.Models.Solicitacao", "Solicitacao")
                        .WithMany("Historico")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("teste.Models.ItemSolicitacao", b =>
                {
                    b.HasOne("teste.Models.Material", "Material")
                        .WithMany("ItensSolicitacao")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("teste.Models.Solicitacao", "Solicitacao")
                        .WithMany("Itens")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("teste.Models.LocalSolicitacao", b =>
                {
                    b.HasOne("teste.Models.CanteiroObra", "CanteiroObra")
                        .WithMany("LocaisSolicitacao")
                        .HasForeignKey("CanteiroObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("teste.Models.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("LocalSolicitacaoId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("LocalSolicitacaoId");

                            b1.ToTable("LocaisSolicitacao");

                            b1.WithOwner()
                                .HasForeignKey("LocalSolicitacaoId");
                        });

                    b.Navigation("CanteiroObra");

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("teste.Models.Maquinario", b =>
                {
                    b.HasOne("teste.Models.CanteiroObra", "CanteiroObra")
                        .WithMany("Maquinarios")
                        .HasForeignKey("CanteiroObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("teste.Models.Localizacao", "LocalizacaoAtual", b1 =>
                        {
                            b1.Property<int>("MaquinarioId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("MaquinarioId");

                            b1.ToTable("Maquinarios");

                            b1.WithOwner()
                                .HasForeignKey("MaquinarioId");
                        });

                    b.Navigation("CanteiroObra");

                    b.Navigation("LocalizacaoAtual");
                });

            modelBuilder.Entity("teste.Models.Solicitacao", b =>
                {
                    b.HasOne("teste.Models.Apontador", "Apontador")
                        .WithMany("SolicitacoesGerenciadas")
                        .HasForeignKey("ApontadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("teste.Models.CanteiroObra", "CanteiroObra")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("CanteiroObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teste.Models.Deposito", "Deposito")
                        .WithMany()
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("teste.Models.LocalSolicitacao", "LocalSolicitacao")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("LocalSolicitacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("teste.Models.Maquinario", "Maquinario")
                        .WithMany("SolicitacoesAtribuidas")
                        .HasForeignKey("MaquinarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("teste.Models.Solicitador", "Solicitador")
                        .WithMany("SolicitacoesCriadas")
                        .HasForeignKey("SolicitadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apontador");

                    b.Navigation("CanteiroObra");

                    b.Navigation("Deposito");

                    b.Navigation("LocalSolicitacao");

                    b.Navigation("Maquinario");

                    b.Navigation("Solicitador");
                });

            modelBuilder.Entity("teste.Models.Usuario", b =>
                {
                    b.HasOne("teste.Models.CanteiroObra", "CanteiroObra")
                        .WithMany("Usuarios")
                        .HasForeignKey("CanteiroObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanteiroObra");
                });

            modelBuilder.Entity("teste.Models.OperadorMaquinario", b =>
                {
                    b.HasOne("teste.Models.Maquinario", "MaquinarioAtual")
                        .WithOne("OperadorAtual")
                        .HasForeignKey("teste.Models.OperadorMaquinario", "MaquinarioAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MaquinarioAtual");
                });

            modelBuilder.Entity("teste.Models.CanteiroObra", b =>
                {
                    b.Navigation("Depositos");

                    b.Navigation("LocaisSolicitacao");

                    b.Navigation("Maquinarios");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("teste.Models.Deposito", b =>
                {
                    b.Navigation("EstoqueMateriais");
                });

            modelBuilder.Entity("teste.Models.LocalSolicitacao", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("teste.Models.Maquinario", b =>
                {
                    b.Navigation("OperadorAtual");

                    b.Navigation("SolicitacoesAtribuidas");
                });

            modelBuilder.Entity("teste.Models.Material", b =>
                {
                    b.Navigation("EstoquesMateriais");

                    b.Navigation("ItensSolicitacao");
                });

            modelBuilder.Entity("teste.Models.Solicitacao", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("teste.Models.Apontador", b =>
                {
                    b.Navigation("SolicitacoesGerenciadas");
                });

            modelBuilder.Entity("teste.Models.Solicitador", b =>
                {
                    b.Navigation("SolicitacoesCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
